version: '3'
services:
  go:
    image: golang:1.13
    container_name: goauthapp
    volumes:
      - .:/goauth
    working_dir: /goauth
    command: ./build.sh
    links:
      - postgres
    ports:
      - 8080:8080
    environment:
      URL: "https://red.bomaidea.xyz/todoAPI/"
  postgres:
    image: postgres
    container_name: goauthdb
    restart: always
    environment:
      POSTGRES_DB: goauthdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - ./db:/postgres